package ru.MrEnthropia.Azurite.models;

public enum Category {
    TOOL,
    ELECTRIC_TOOL,
    LIQUID_IN_CONTAINER,
    LIQUID_IN_BOTTLE,
    CONSUMABLES,
    MECHANICAL_SPARE_PARTS,
    PLUMBING_SPARE_PARTS,
    ELECTRICAL_AND_ELECTRONICS,
    CABLE,
    OTHER
}
